### ISSUE TITLE
Services and Settings Should Persist Across Restarts

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ood-images-full#1]
Immediately after provisioning these images work as expected. If the boxes are ever reloaded then selinux is back to enforcing and several key services are not running.

Things that need fixing on all:

* [ ] selinux settings persist
* [ ] munged service starts on boot

Needs fixing on `ood`:

* [ ] httpd24 service starts on boot

Needs fixing on `head`:

* [ ] slurmd service starts on boot
* [ ] slurmctld service starts on boot

**Comment by ericfranz** [comment]
I think this work is good especially as these vms are starting to play a bigger role in development than before. I did most of my work on Passenger 5 using the ood-images vm.

Whatever we do here should probably be propgated to the ood-images Vagrant image (as appropriate).

**Comment by treydock** [comment]
For SELinux issue, maybe the logic in `ood-setup.sh` and `head-setup.sh` is silently being skipped because the logic was originally intended to not change things in Docker.  I think always running the two `sed` commands should be fine.

**Comment by treydock** [comment]
munge should be starting at boot, if it's not then something is very wrong.  The `slurm-setup.sh` has `systemctl enable munge`.  The Vagrantfile does `systemctl enable httpd24-httpd` for the `ood` VM.  The Vagrantfile is doing `systemctl enable` for both `slurmctld` and `slurmd` for `head`.  So why these services are not persisting through reboots may be something else wrong with the VMs.

**Comment by treydock** [comment]
@ericfranz Why use `ood-images` Vagrant image and not these?  Is there functionality in `ood-images` missing from here?

**Comment by treydock** [comment]
@MorganRodgers I'm experimenting with shared slurm for #2 and also seeing why the SELinux change isn't persisting.

**Comment by MorganRodgers** [comment]
I just noticed that my master branch was stale. I had cloned at https://github.com/OSC/ood-images-full/commit/6ea86b70543b3a521e915107d66f042c5ad2c498 and had missed that you had fixed these very issues. I need to retest, but this is probably all taken care of.

**Comment by treydock** [comment]
I think service startup on boot is resolved. I'm messing with the images for #3 and #2 and am noticing daemons are running after `vagrant reload`.  I have simplified logic in place that should fix SELinux since previous logic was complicated to avoid errors on Docker.

**Comment by treydock** [comment]
@MorganRodgers I pushed new commit that should address all open issues.  I've tested a bit on my local system but could use a separate set of eyes.

**Comment by MorganRodgers** [comment]
Thanks @treydock . I'm using the VMs at the moment but I'll test it when I have a moment.

**Comment by MorganRodgers** [comment]
@treydock it looks to me like these are all taken care of. Thanks for looking this over.
