### ISSUE TITLE
Unable to execute setup

### ISSUE THREAD

**Issue by codingS3b** [OSC/ood-images-full#10]
Not sure if this is the correct place for the issue but I am unable to execute the command (stated in the README.md file)
```
vagrant plugin install vagrant-vbguest
```
which aborts with errors like
```
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies fog-core (~> 1.43.0) and fog-core (= 1.45.0)
  Activated fog-core-1.45.0
  which does not match conflicting dependency (~> 1.43.0)

  Conflicting dependency chains:
    fog-core (= 1.45.0), 1.45.0 activated

  versus:
    vagrant-libvirt (> 0), 0.0.41 activated, depends on
    fog-core (~> 1.43.0)
```
Could you provide me with any hints on how to solve that?
I am using Ubuntu 18.04 with vagrant 2.0.2 installed via `apt-get`.

**Comment by treydock** [comment]
That looks like an issue with plugins unrelated to `vagrant-vbguest` because as far as I can tell the only dependency for `vagrant-vbguest` is `micromachine`. Maybe try `vagrant plugin repair` and see if you're able to fix your plugin installation.

**Comment by codingS3b** [comment]
Thanks for the hint. I tried your suggestion, unfortunately without success, still getting the same errors. From looking at the vagrant side, this seems to be a known issue: https://github.com/dotless-de/vagrant-vbguest/issues/292. Upgrading to vagrant 2.0.3 solved the problem.
