### ISSUE TITLE
Experiment with building Slurm in a shared directory

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ood-images-full#2]
In this example installation Slurm needs to be built and then installed on each system. If it is at all performant to build Slurm in the shared directory, or copy the build directory to the shared space, then the build could be shared between `head` and `ood` reducing time spent in `vagrant up`.

Using [Vagrant triggers](https://www.vagrantup.com/docs/triggers/) it is possible to perform actions after `vagrant up` completes, which could be used to clean up the shared directory if desired.

**Comment by treydock** [comment]
I think always provisioning `head` VM first and letting that one build SLURM somewhere in shared directory would be enough.

With other `synced_folder` settings could add `config.vm.synced_folder "./slurm", "/opt/slurm", type: "virtualbox`.  The current `slurm-setup.sh` for `ood` VM would skip building if it detects slurm is already installed.

**Comment by treydock** [comment]
Using shared folder won't work because the shared folder is mounted AFTER services start at boot, I think.  I am experimenting with updating `slurm-setup.sh` to copy the build to /vagrant/slurm and then install /vagrant/slurm if it's built.

**Comment by MorganRodgers** [comment]
I'll test this tomorrow.

**Comment by MorganRodgers** [comment]
@treydock works for me, and the `/etc/profile.d` addition is a nice touch too. Thanks!
