### ISSUE TITLE
Dependency Errors on Installation

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ood-images-full#6]
I was getting an error about `scl` not being found despite `centos-scl-release` being installed. `scl_utils` provides the `scl` command.

After installing `scl_utils` I am now getting an error during Passenger installation about the Gem Rack being missing:

TLDR:
```
    ood: Error: Package: passenger-5.3.7-1.el7.x86_64 (ondemand-web)
    ood:            Requires: rubygem(rack)
```

I do not get these errors when directly installing our RPMs.

**Comment by treydock** [comment]
Is the EPEL repo installed?  I think `rubygem(rack)` comes from EPEL. We used to install EPEL to get munge but that happens after ondemand install.  Pushed commit that adds `epel-release` during first provision step.

**Comment by MorganRodgers** [comment]
It's still running, but I think that fixes it.

**Comment by MorganRodgers** [comment]
Confirmed working. Thanks @treydock.
